name: rave_flutter
description: A new Flutter plugin for making payment with Flutterwave's rave.
version: 0.0.9-alpha+2
homepage: https://github.com/wilburt/rave_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  http: ^0.13.4
  intl: ^0.17.0
  meta: ^1.1.8
  async: ^2.4.2
  dio: ^4.0.4
  get_it: ^7.2.0
  equatable: ^2.0.3
  tripledes_nullsafety: ^1.0.1
  webview_flutter: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterwave.rave_flutter
        pluginClass:  RaveFlutterPlugin
      ios:
        pluginClass:  RaveFlutterPlugin

  assets:
    - assets/images/
